name: summaCI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t sebastiannavia/micro-calculadora-suma:${{ github.run_number }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push into Docker-hub
      run: docker push sebastiannavia/micro-calculadora-suma:${{ github.run_number }}
